Description: "Cloudformation template deployment"

Parameters:

  FunctionName:
    Description: 'Name of the python file in this case'
    Type: String
  HandlerName:
    Description: 'Function called from python file'
    Type: String
  S3Bucket:
    Description: 'Bucket name'
    Type: String
  S3Key:
    Description: 'Name of the file in th S3 bucket'
    Type: String
  RoleName:
    Description:  'Name of the role the function is executed with'
    Type: String
  MemorySize:
    Description: 'Memory size used'
    Type: Number
  TimeOut:
    Description: 'Timeout for the call'
    Type: Number
  SecurityGroups:
    Description: 'SecurityGroups'
    Type: List<AWS::EC2::SecurityGroup::Id>
  SubNetIds:
    Description: 'SubNetIds'
    Type: List<AWS::EC2::Subnet::Id>

Resources:

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: {Ref: S3Bucket}
        S3Key: {Ref: S3Key}
      Handler: {Ref: HandlerName}
      FunctionName: {Ref: FunctionName}
      MemorySize: {Ref: MemorySize}
      Role: {Ref: RoleName}
      Runtime: python2.7
      Timeout: {Ref: TimeOut}
      VpcConfig:
        SecurityGroupIds: {Ref: SecurityGroups}
        SubnetIds: {Ref: SubNetIds}
